export const stats = [
  { label: "Properties Sold", value: "50+" },
  { label: "Happy Clients", value: "120+" },
  { label: "Years Experience", value: "7+" },
  { label: "Cities Covered", value: "8+" },
];

export const featuredProperties = [
  {
    id: 1,
    title: "Fully furnished terraces, Ikate",
    image: "/images/house-1.jpeg",
    type: "For Sale",
    location: "Lagos, Nigeria",
    price: "₦250million",
    bedrooms: 3,
    bathrooms: 3,
    area: "350m²",
    features: ["Swimming Pool", "Garage", "Furnished", "C of O", "Survey Plan"],
  },
  {
    id: 2,
    title: "Land in Rayfield",
    image: "/images/land-one.jpg",
    type: "For Sale",
    location: "Jos, Nigeria",
    price: "Low as #2,000,000",
    bedrooms: null,
    bathrooms: null,
    area: "500m²",
    features: ["C of O", "Survey Plan", "Water Access"],
  },

  {
    id: 3,
    title: "Royal Pine estate orchid",
    images: [
      "/images/sitting-room-1.jpeg",
      "/images/sitting-room-2.jpeg",
      "/images/dining-1.jpeg",
      "/images/room-1.jpeg",
      "/images/room-2.jpeg",
      "/images/kitchen-1.jpeg",
      "/images/bathroom-1.jpeg",
    ],
    type: "Short-let",
    location: "Lagos, Nigeria",
    price: "₦175,000/night",
    bedrooms: 3,
    bathrooms: 2,
    area: "180m²",
    features: ["Furnished", "Gym Access", "Swimming Pool"],
  },
];

export const propertyData = {
  Lands: [
    {
      id: 1,
      title: "Land in Rayfield",
      image: "/images/land-one.jpg",
      type: "For Sale",
      location: "Jos, Nigeria",
      price: "Low as #2,000,000",
      bedrooms: null,
      bathrooms: null,
      area: "500m²",
      features: ["C of O", "Survey Plan", "Water Access"],
    },
    {
      id: 2,
      title: "Land in Gold and Base",
      image: "/images/land-two.jpg",
      type: "For Sale",
      location: " Jos, Nigeria",
      price: "Low as #2,000,000",
      bedrooms: null,
      bathrooms: null,
      area: "500m²",
      features: ["C of O", "Survey Plan", "Water Access"],
    },
    {
      id: 3,
      title: "Land in Guratop",
      image: "/images/land-three.jpg",
      type: "For Sale",
      location: " Jos, Nigeria",
      price: "Low as #2,000,000",
      bedrooms: null,
      bathrooms: null,
      area: "500m²",
      features: ["C of O", "Survey Plan", "Water Access"],
    },
    {
      id: 4,
      title: "Land in Ibeju Lekki",
      image: "/images/land-four.jpg",
      type: "For Sale",
      location: " Lagos Nigeria",
      price: "Low as #2,000,000",
      bedrooms: null,
      bathrooms: null,
      area: "500m²",
      features: ["C of O", "Survey Plan", "Water Access"],
    },
    {
      id: 5,
      title: "Land in Lamingo",
      image: "/images/land-five.jpg",
      type: "For Sale",
      location: " Jos Nigeria",
      price: "Low as #2,000,000",
      bedrooms: null,
      bathrooms: null,
      area: "500m²",
      features: ["C of O", "Survey Plan", "Water Access"],
    },
    {
      id: 6,
      title: "Land in Ibeju Lekki",
      image: "/images/land-five.jpg",
      type: "For Sale",
      location: "Lagos, Nigeria",
      price: "Low as #2,000,000",
      bedrooms: null,
      bathrooms: null,
      area: "500m²",
      features: ["C of O", "Survey Plan", "Water Access"],
    },
  ],
  Houses: [
    {
      id: 1,
      title: "Fully furnished terraces, Ikate",
      image: "/images/house-1.jpeg",
      type: "For Sale",
      location: "Lekki Lagos, Nigeria",
      price: "₦250million",
      bedrooms: 3,
      bathrooms: 3,
      area: "350m²",
      features: [
        "Swimming Pool",
        "Garage",
        "Furnished",
        "C of O",
        "Survey Plan",
      ],
    },
  ],
  "Short-lets": [
    {
      id: 3,
      title: "Royal Pine estate orchid",
      images: [
        "/images/sitting-room-1.jpeg",
        "/images/sitting-room-2.jpeg",
        "/images/dining-1.jpeg",
        "/images/room-1.jpeg",
        "/images/room-2.jpeg",
        "/images/kitchen-1.jpeg",
        "/images/bathroom-1.jpeg",
      ],
      type: "Short-let",
      location: "Lagos, Nigeria",
      price: "₦175,000/night",
      bedrooms: 3,
      bathrooms: 2,
      area: "180m²",
      features: ["Furnished", "Gym Access", "Swimming Pool"],
    },
    {
      id: 4,
      title: "The Cove Lekki 1",
      images: [
        "/images/sitting-1.jpeg",
        "/images/dining-1-1.jpeg",
        "/images/room-1-1.jpeg",
        "/images/kitchen-1-1.jpeg",
      ],
      type: "Short-let",
      location: "Lagos, Nigeria",
      price: "₦190,000/night",
      bedrooms: 3,
      bathrooms: 2,
      area: "180m²",
      features: ["Furnished", "Gym Access", "Swimming Pool"],
    },
    {
      id: 5,
      title: "The Cove Lekki 1",
      images: [
        "/images/sitting-2.jpeg",
        "/images/dining-2-1.jpeg",
        "/images/room-2.jpeg",
        "/images/kitchen-2-1.jpeg",
      ],
      type: "Short-let",
      location: "Lagos, Nigeria",
      price: "#175,000/night",
      bedrooms: 3,
      bathrooms: 2,
      area: "180m²",
      features: ["Furnished", "Gym Access", "Swimming Pool"],
    },
  ],
};

export const testimonials = [
  {
    id: 1,
    name: "Chinonso E.",
    role: "First-time Homeowner",
    message:
      "I never thought buying land in Lagos could be this stress-free. NGlobal Properties guided me every step of the way and delivered exactly what they promised.",
    image: "https://github.com/shadcn.png",
  },
  {
    id: 2,
    name: "Amaka O.",
    role: "Investor",
    message:
      "Their transparency and professionalism gave me confidence to invest. My property value has already increased in just a year.",
    image: "https://github.com/evilrabbit.png",
  },
  {
    id: 3,
    name: "Tunde A.",
    role: "Luxury Homeowner",
    message:
      "From inspection to handing over the keys, everything was top-class. They helped me secure a beautiful duplex in Abuja with no hidden charges.",
    image: "https://github.com/leerob.png",
  },
  {
    id: 4,
    name: "Musa G.",
    role: "Happy Client",
    message:
      "I was worried about land scams, but NGlobal gave me peace of mind. My documents were processed quickly and without stress.",
    image: "https://github.com/shadcn.png",
  },
  {
    id: 5,
    name: "Ibiso I.",
    role: "Real Estate Investor",
    message:
      "Working with NGlobal Properties has been one of my best investment decisions. Their team is reliable and always delivers on time.",
    image: "https://github.com/evilrabbit.png",
  },
  {
    id: 6,
    name: "Edidiong A.",
    role: "Satisfied Client",
    message:
      "They helped me furnish and rent out my apartment on Airbnb. The returns have been amazing, and I didn’t have to lift a finger.",
    image: "https://github.com/leerob.png",
  },
];

export const services = [
  {
    title: "Luxury Homes",
    description:
      "Beautifully crafted houses that give you comfort, style, and a place to truly call home.",
    icon: "Home",
  },
  {
    title: "Affordable Lands",
    description:
      "Secure prime land locations with flexible payment options tailored to you. ",
    icon: "Map",
  },
  {
    title: "Shortlets & Airbnb",
    description:
      "Fully furnished apartments for stress-free short stays, vacations, or business trips.",
    icon: "Key",
  },
  {
    title: "Consultation & Advisory",
    description:
      "Expert guidance to help you choose the right property with confidence.",
    icon: "Users",
  },
];
